# Generated by Django 4.2.6 on 2023-11-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_incio',
            new_name='data_inicio',
        ),
    ]
