# Generated by Django 4.2.6 on 2023-11-07 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_rename_data_incio_evento_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='evento_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
